info:
  contact: {}
  description: API administrativa generica para um Basic Crud
  title: Basic Crud
  version: "1.0"
paths:
  /enterprise/v1/ping:
    get:
      description: Retorna um pong para verificar se o serviço enterprise está ativo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Healthcheck do Enterprise
      tags:
      - Enterprise
  /user/v1/ping:
    get:
      description: Retorna um pong para verificar se o serviço User está ativo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Healthcheck do User
      tags:
      - User
swagger: "2.0"
